# Generated by Django 3.1.4 on 2020-12-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='picture',
            new_name='image',
        ),
    ]
